/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as CeoRouteImport } from './routes/ceo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeeIndexRouteImport } from './routes/employee/index'
import { Route as CustomerIndexRouteImport } from './routes/customer/index'
import { Route as CeoIndexRouteImport } from './routes/ceo/index'
import { Route as EmployeeProfileRouteImport } from './routes/employee/profile'
import { Route as CustomerProfileRouteImport } from './routes/customer/profile'
import { Route as CustomerHistoryRouteImport } from './routes/customer/history'
import { Route as CustomerDocumentsRouteImport } from './routes/customer/documents'
import { Route as CustomerComplaintsRouteImport } from './routes/customer/complaints'
import { Route as CeoProfileRouteImport } from './routes/ceo/profile'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const CeoRoute = CeoRouteImport.update({
  id: '/ceo',
  path: '/ceo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeRoute,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRoute,
} as any)
const CeoIndexRoute = CeoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CeoRoute,
} as any)
const EmployeeProfileRoute = EmployeeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => EmployeeRoute,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerHistoryRoute = CustomerHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerDocumentsRoute = CustomerDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerComplaintsRoute = CustomerComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => CustomerRoute,
} as any)
const CeoProfileRoute = CeoProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CeoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ceo': typeof CeoRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/employee': typeof EmployeeRouteWithChildren
  '/login': typeof LoginRoute
  '/ceo/profile': typeof CeoProfileRoute
  '/customer/complaints': typeof CustomerComplaintsRoute
  '/customer/documents': typeof CustomerDocumentsRoute
  '/customer/history': typeof CustomerHistoryRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/ceo/': typeof CeoIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/employee/': typeof EmployeeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ceo/profile': typeof CeoProfileRoute
  '/customer/complaints': typeof CustomerComplaintsRoute
  '/customer/documents': typeof CustomerDocumentsRoute
  '/customer/history': typeof CustomerHistoryRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/ceo': typeof CeoIndexRoute
  '/customer': typeof CustomerIndexRoute
  '/employee': typeof EmployeeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ceo': typeof CeoRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/employee': typeof EmployeeRouteWithChildren
  '/login': typeof LoginRoute
  '/ceo/profile': typeof CeoProfileRoute
  '/customer/complaints': typeof CustomerComplaintsRoute
  '/customer/documents': typeof CustomerDocumentsRoute
  '/customer/history': typeof CustomerHistoryRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/ceo/': typeof CeoIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/employee/': typeof EmployeeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ceo'
    | '/customer'
    | '/employee'
    | '/login'
    | '/ceo/profile'
    | '/customer/complaints'
    | '/customer/documents'
    | '/customer/history'
    | '/customer/profile'
    | '/employee/profile'
    | '/ceo/'
    | '/customer/'
    | '/employee/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ceo/profile'
    | '/customer/complaints'
    | '/customer/documents'
    | '/customer/history'
    | '/customer/profile'
    | '/employee/profile'
    | '/ceo'
    | '/customer'
    | '/employee'
  id:
    | '__root__'
    | '/'
    | '/ceo'
    | '/customer'
    | '/employee'
    | '/login'
    | '/ceo/profile'
    | '/customer/complaints'
    | '/customer/documents'
    | '/customer/history'
    | '/customer/profile'
    | '/employee/profile'
    | '/ceo/'
    | '/customer/'
    | '/employee/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CeoRoute: typeof CeoRouteWithChildren
  CustomerRoute: typeof CustomerRouteWithChildren
  EmployeeRoute: typeof EmployeeRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceo': {
      id: '/ceo'
      path: '/ceo'
      fullPath: '/ceo'
      preLoaderRoute: typeof CeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/': {
      id: '/employee/'
      path: '/'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/customer/': {
      id: '/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/ceo/': {
      id: '/ceo/'
      path: '/'
      fullPath: '/ceo/'
      preLoaderRoute: typeof CeoIndexRouteImport
      parentRoute: typeof CeoRoute
    }
    '/employee/profile': {
      id: '/employee/profile'
      path: '/profile'
      fullPath: '/employee/profile'
      preLoaderRoute: typeof EmployeeProfileRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/customer/profile': {
      id: '/customer/profile'
      path: '/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/history': {
      id: '/customer/history'
      path: '/history'
      fullPath: '/customer/history'
      preLoaderRoute: typeof CustomerHistoryRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/documents': {
      id: '/customer/documents'
      path: '/documents'
      fullPath: '/customer/documents'
      preLoaderRoute: typeof CustomerDocumentsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/complaints': {
      id: '/customer/complaints'
      path: '/complaints'
      fullPath: '/customer/complaints'
      preLoaderRoute: typeof CustomerComplaintsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/ceo/profile': {
      id: '/ceo/profile'
      path: '/profile'
      fullPath: '/ceo/profile'
      preLoaderRoute: typeof CeoProfileRouteImport
      parentRoute: typeof CeoRoute
    }
  }
}

interface CeoRouteChildren {
  CeoProfileRoute: typeof CeoProfileRoute
  CeoIndexRoute: typeof CeoIndexRoute
}

const CeoRouteChildren: CeoRouteChildren = {
  CeoProfileRoute: CeoProfileRoute,
  CeoIndexRoute: CeoIndexRoute,
}

const CeoRouteWithChildren = CeoRoute._addFileChildren(CeoRouteChildren)

interface CustomerRouteChildren {
  CustomerComplaintsRoute: typeof CustomerComplaintsRoute
  CustomerDocumentsRoute: typeof CustomerDocumentsRoute
  CustomerHistoryRoute: typeof CustomerHistoryRoute
  CustomerProfileRoute: typeof CustomerProfileRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerComplaintsRoute: CustomerComplaintsRoute,
  CustomerDocumentsRoute: CustomerDocumentsRoute,
  CustomerHistoryRoute: CustomerHistoryRoute,
  CustomerProfileRoute: CustomerProfileRoute,
  CustomerIndexRoute: CustomerIndexRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface EmployeeRouteChildren {
  EmployeeProfileRoute: typeof EmployeeProfileRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
}

const EmployeeRouteChildren: EmployeeRouteChildren = {
  EmployeeProfileRoute: EmployeeProfileRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
}

const EmployeeRouteWithChildren = EmployeeRoute._addFileChildren(
  EmployeeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CeoRoute: CeoRouteWithChildren,
  CustomerRoute: CustomerRouteWithChildren,
  EmployeeRoute: EmployeeRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
